=== Arcle1/linterhub/hub/.schema/args.json
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "title": "This schema describes the engine arguments schema",
    "description": "The engine arguments schema",
    "type": "object",
    "$ref": "http://json-schema.org/draft-04/schema",
    "properties": {
        "$schema": {
        },
        "type": {
        },
        "allOf": {
        },
        "id": {
            "type": "string",
            "description": "The engine id"  
        },
        "definitions": {
            "description": "The arguments definitions",
            "type": "object",
            "$ref": "http://json-schema.org/draft-04/schema",
            "properties": {
                "cmd": {
                    "type": "object",
                    "description": "The specific configuraton for cmd",
                    "properties": {
                        "executable": {
                            "type": "string",
                            "description": "The engine executable, by default equal to the engine name"
                        },
                        "masks": {
                            "type": "boolean",
                            "description": "Can use masks for multiple files analyze",
                            "default": true
                        },
                        "success": {
                            "type": "integer",
                            "description": "The success exit code",
                            "default": 0
                        },
                        "version": {
                            "type": "string",
                            "description": "The engine version, equal to the output of version command"
                        }   
                    }
                },
                "options": {
                    "type": "object",
                    "description": "The engine options",
                    "$ref": "http://json-schema.org/draft-04/schema"
                },
                "section": {
                    "type": "object",
                    "description": "The engine configuration section",
                    "$ref": "http://json-schema.org/draft-04/schema"
                }
            },
            "required": [
                "section"
            ],
            "additionalProperties": false
        }
    },
    "required": [
        "id",
        "definitions"
    ],
    "additionalProperties": false
}

=== Arcle1/linterhub/hub/jshint/args.json
{
    "$schema": "./../.schema/args.json",
    "id": "jshint",
    "type": "object",
    "allOf": [
        {
            "$ref": "#/definitions/options"
        }
    ],
    "definitions": {
        "cmd": {
            "success": 2,
            "version": "jshint v2.9.5"
        },
        "options": {
            "type": "object",
            "properties": {
                "--config": {
                    "id": "linterhub:config",
                    "type": "string",
                    "description": "Custom configuration file"
                },
                "--reporter": {
                    "type": "string",
                    "description": "Custom reporter",
                    "oneOf": [
                        {
                            "type": "string",
                            "enum": [
                                "jslint",
                                "checkstyle",
                                "unix"
                            ]
                        },
                        {
                            "type": "string",
                            "format": "uri"
                        }
                    ]
                },
                "--prereq": {
                    "id": "arg:--prereq",
                    "type": "string",
                    "description": "Comma-separate list of prerequisite (paths). E.g. files which include definitions of global variables used throughout your project"
                },
                "--exclude": {
                    "id": "arg:--exclude",
                    "type": "string",
                    "description": "Exclude files matching the given filename pattern"
                },
                "--exclude-path": {
                    "id": "arg:--exclude-path",
                    "type": "string",
                    "description": "Pass in a custom jshintignore file path"
                },
                "--filename": {
                    "id": "arg:--filename",
                    "type": "string",
                    "description": "Pass in a filename when using STDIN to emulate config lookup for that file name"
                },
                "--verbose": {
                    "id": "arg:--verbose",
                    "type": "null",
                    "description": "Show message codes"
                },
                "--show-non-errors": {
                    "id": "arg:--show-non-errors",
                    "type": "null",
                    "description": "Show additional data generated by jshint"
                },
                "--extra-ext": {
                    "id": "arg:--extra-ext",
                    "type": "string",
                    "description": "Comma-separated list of file extensions to use"
                },
                "--extract": {
                    "id": "arg:--extract",
                    "type": "string",
                    "description": "Extract inline scripts contained in HTML",
                    "enum": [
                        "auto",
                        "always",
                        "never"
                    ],
                    "default": "never"
                },
                "-": {
                    "id": "linterhub:stdin",
                    "type": "null",
                    "description": "Read source from standard input"
                },
                "--help": {
                    "type": "string",
                    "description": "Show help"
                },
                "--version": {
                    "id": "linterhub:version",
                    "type": "string",
                    "description": "Show version"
                },
                "": {
                    "id": "linterhub:path",
                    "type": "string",
                    "description": "Path for analysis"
                }
            }
        },
        "section": {
            "type": "object",
            "description": "The engine configuration section",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "The engine name",
                    "enum": [
                        "jshint"
                    ]
                },
                "options": {
                    "type": "object",
                    "description": "The engine configuration",
                    "$ref": "#/definitions/options"
                }
            }
        }
    }
}
